# NEO4J GRAPH DB CONFIGURATION
spring.neo4j.uri=${DEV_DB_URI}
spring.neo4j.authentication.username=${DEV_DB_USERNAME}
spring.neo4j.authentication.password=${DEV_DB_PASSWORD}

# JWT RELATED PARAMS
jwt.expirationMs=3600000
jwt.refreshExpirationMS=86400000
jwt.secret=${JWT_SECRET}

# CORS CONFIGURATION
frontend.urls=http://localhost:5173