# NEO4J GRAPH DB CONFIGURATION
spring.neo4j.uri=${DEV_DB_URI}
spring.neo4j.authentication.username=${DEV_DB_USERNAME}
spring.neo4j.authentication.password=${DEV_DB_PASSWORD}

# JWT RELATED PARAMS
#jwt.expirationMs=60000
#jwt.refreshExpirationMS=180000
jwt.expirationMs=3600000
jwt.refreshExpirationMS=86400000
jwt.secret=${JWT_SECRET}

# CORS CONFIGURATION
frontend.urls=http://localhost:5173

# SMTP CONFIGURATION
spring.mail.host=${SMTP_SERVER}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_LOGIN}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true