# NEO4J GRAPH DB CONFIGURATION
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=${DEV_DB_USERNAME}
spring.neo4j.authentication.password=${DEV_DB_PASSWORD}

# JWT RELATED PARAMS
jwt.expirationMs=60000
jwt.refreshExpirationMS=120000
jwt.secret=${JWT_SECRET}

# CORS CONFIGURATION
frontend.urls=http://localhost:3000

# SMTP CONFIGURATION