# NEO4J GRAPH DB CONFIGURATION
spring.neo4j.uri=${PROD_DB_URI}
spring.neo4j.authentication.username=${PROD_DB_USERNAME}
spring.neo4j.authentication.password=${PROD_DB_PASSWORD}

# JWT RELATED PARAMS
# SMTP CONFIGURATION